course_name = "学术规范与论文写作"
course_code = "WRCO4024"
repo_type = "normal"

[lecturers]

[[lecturers.items]]
name = "苗子博"

[[lecturers.items.reviews]]
content = "授课风格：进行一两次考勤，但提问有时会直接指定在场的学生回答。"
author = { name = "345ljh", link = "https://www.github.com/345ljh", date = "2026-08" }

[[sections]]
title = "课程内容"

[[sections.items]]
content = """
### 课程内容
包括学术研究的基本知识、科技文献的阅读与检索方法、学术/学位论文的撰写、学位论文的格式与规范。
"""

[[sections]]
title = "关于考试"

[[sections.items]]
content = """
成绩构成：平时表现（包括2次作业）50%，期末考试50%。

- 期末考试  
  - 基本是课件中涉及的内容，全开卷（可携带任意纸质材料参加考试，不限页数）。```note```目录下仍提供整理课件得到的A4纸。
"""
author = { name = "345ljh", link = "https://www.github.com/345ljh", date = "2026-08" }
